name: Build curl bundle

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            name: Windows
            tls: openssl
            rust-targets: x86_64-pc-windows-msvc
            extra-args: --perl-path C:/Strawberry/perl/bin/perl.exe

          - os: macos-latest
            platform: macos
            name: macOS (universal)
            tls: openssl
            rust-targets: x86_64-apple-darwin,aarch64-apple-darwin

          - os: macos-latest
            platform: ios
            name: iOS
            tls: openssl
            rust-targets: aarch64-apple-ios

          - os: ubuntu-latest
            platform: android32
            name: Android (32-bit)
            tls: openssl
            rust-targets: armv7-linux-androideabi

          - os: ubuntu-latest
            platform: android64
            name: Android (64-bit)
            tls: openssl
            rust-targets: aarch64-linux-android

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v6

      - name: Cache cargo executables
        if: matrix.tls == 'rustls'
        uses: actions/cache@v3
        id: cargo-cache
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-v1

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Install LLVM
        if: matrix.platform == 'windows'
        uses: egor-tensin/setup-clang@v2
        with:
          version: 21

      - name: Install Rust
        if: matrix.tls == 'rustls'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-targets }}

      - name: Install cargo-c
        if: matrix.tls == 'rustls' && steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-c

      # Android setup
      - name: Install NDK
        if: startsWith(matrix.platform, 'android')
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29

      # Build
      - name: Run build script
        run: python build.py --generator Ninja --flat-output --lto --platform ${{ matrix.platform }} --tls ${{ matrix.tls }} ${{ matrix.extra-args }}

      # Upload
      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: curl-${{ matrix.platform }}
          path: out/${{ matrix.platform }}
